INSERT INTO ldk_test (NOTICE_ID, TITLE, IMPORTANT, TOPPED, STATUS, PUBLISH_TIME, CONTENT, READ_NUM, AID, CREATOR, CDATE, UPDATOR, UDATE, MARK)
VALUES('111', 'test001', 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO ldk_test (NOTICE_ID, TITLE, IMPORTANT, TOPPED, STATUS, PUBLISH_TIME, CONTENT, READ_NUM, AID, CREATOR, CDATE, UPDATOR, UDATE, MARK)
VALUES('222', 'test002', 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 1);

INSERT INTO ldk_test2 (ID, INSPECTION_TABLE_NAME, INSPECTION_PLACE, GENERAL_ITEMS, IMPORTANT_ITEMS, OTHER_ITEMS, SIGNATURE_SETTING, CREATE_TIME, UPDATE_TIME, DEL_FLAG)
VALUES('aaa', 'a', '1', '2', '3', '4', '5', NULL, NULL, 1);
INSERT INTO ldk_test2 (ID, INSPECTION_TABLE_NAME, INSPECTION_PLACE, GENERAL_ITEMS, IMPORTANT_ITEMS, OTHER_ITEMS, SIGNATURE_SETTING, CREATE_TIME, UPDATE_TIME, DEL_FLAG)
VALUES('bbb', 'a', '1', '2', '3', '4', '5', NULL, NULL, 1);

